apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management-service
        image: inventory-management-service:latest
        ports:
        - containerPort: 80
